### PR TITLE
Modified 4.-documentation/e2.configure-redirects.md

### PR DESCRIPTION
**Pull request by sydstoplight**
Added a section on permalinks and permalink ID's with screenshot. Polished rest of page.

### CODE REVIEW

**Review by pamgoodrich — CHANGES_REQUESTED** [review]
A few small doc changes. The technical doc looks really good. Can you let me know who did the technical review?

**Comment by sydstoplight** [comment]
I'll get started on these edits. The technical redirects instructions were on the existing page. I pulled added content about permalinks from the Slack convos explaining how they worked.

**Comment by pamgoodrich** [comment]
OK... I had Nauman take a look at this. The content is mostly correct, but the link format is for all links, not just for people who chose to use redirects. Can you move the sections on permalinks here:

https://meta.stoplight.io/docs/platform/branches/sydney-266-redirects/ZG9jOjM3MTUzNDgy-add-links-to-articles

and work it into the tips section at the bottom? You might need to reformat the content a bit. 

Also, instead of this:

Adding redirect rules to documentation pages creates a permalink for identification.

You may want to say:

When you publish documentation, permalinks are added to URLs for identification.

**Review by pamgoodrich — APPROVED** [review]
@sydstoplight : I made one small tweak to this. If you change the name of the file, the permalinks change. You can change the article title without impact, however.

I will merge this now.

Thank you!

**Pull request merged**
