### PR TITLE
Add minimum version supported of Azure DevOps Server

### PR DESCRIPTION
**Pull request by heitortsergent**
Adding the minimum version we support for Azure DevOps Server/TFS.

Based on this discussion: https://stoplight-internal.slack.com/archives/C0258SZH9SB/p1658780121985039

### CODE REVIEW

**Review by rainum — APPROVED** [review]
Looks good to me 👍 Should we mention the maximum version as well? 

https://github.com/stoplightio/platform-internal/blob/v2/packages/integrations/src/providers/azure-devops-server/api/endpoints.ts#L13

**Comment by heitortsergent** [comment]
@rainum ah, that's probably a good idea.

From that file you linked to, does it mean we only support TFS 2018 Update 2 and TFS 2018 Update 3 then? If that's the case I can list those two versions instead of saying minimum and maximum.

**Comment by rainum** [comment]
> From that file you linked to, does it mean we only support TFS 2018 Update 2 and TFS 2018 Update 3 then? If that's the case I can list those two versions instead of saying minimum and maximum.

Sure, let's list two versions instead 👍  I haven’t thought about that haha

**Comment by heitortsergent** [comment]
@rainum alright, thanks! I updated the PR so we only list the two versions.

**Pull request merged**
